service: email-subscribe

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 10
  stage: dev
  region: eu-central-1

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.run
    events:
      - http:
          path: /
          method: post
